[project]
name = "map-charting-student-math-misunderstandings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autoawq>=0.2.9",
    "bitsandbytes>=0.48.1",
    "datasets>=4.0.0",
    "deepspeed>=0.17.5",
    "dotenv>=0.9.9",
    "isort>=6.0.1",
    "kaggle>=1.7.4.5",
    "openai>=1.90.0",
    "pandas>=2.3.2",
    "peft>=0.17.1",
    "ruff>=0.12.12",
    "scikit-learn>=1.7.1",
    "trl>=0.19.1",
    "vllm==0.8.5.post1",
    "wandb>=0.21.3",
]

[project.optional-dependencies]
flash-attn = ["flash-attn==2.7.2.post1"]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.uv.workspace]
members = [
    "use_awq",
    "use_gptqmodel",
    "use_gptq",
    "use_autoround",
]
