[project]
name = "map-charting-student-math-misunderstandings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]
